### ISSUE TITLE
JID parsing incorrect

### ISSUE THREAD

**Issue by lloydwatkin** [node-xmpp/node-xmpp-core#49]
```javascript
> j = new jid('lloyd.watkin@somewhere/something@blah/ hello')
{ local: 'lloyd.watkin\\40somewhere\\2fsomething',
  domain: 'blah',
  resource: ' hello',
  user: 'lloyd.watkin\\40somewhere\\2fsomething' }
```

Should have resulted in:

```javascript
{ local: 'lloyd.watkin',
  domain: 'somewhere',
  resource: ' something@blah/ hello',
  user: 'lloyd.watkin' }
```

**Comment by flosse** [comment]
hey, what do you think about using a separate jid module? It could be used in other projects too, e.g. [there is an outdated fork](https://github.com/flosse/strophejs-plugins/blob/master/joap/jid.coffee) used for a strophe plugin.
[Here is a current fork](https://github.com/flosse/node-jid) that also fixes #49.

**Comment by chris-rock** [comment]
I like the idea, if it provides additional value. Why not use node-xmpp-core?

**Comment by flosse** [comment]
> I like the idea, if it provides additional value.

of course I think it provides additional value ;-)

> Why not use node-xmpp-core?

e.g. for a strophe.js plugin I don't want to require a whole library, I just need that little but stable and up to date snippet.

**Comment by chris-rock** [comment]
But strophe ships with its own JID implementation? Why use another? I am just curious

**Comment by flosse** [comment]
> But strophe ships with its own JID implementation? Why use another? I am just curious

yes, strophe has e.g. `getResourceFromJid()` but no `JID` object that e.g. takes care of cases like `xn--ko-eka`. And I like the `JID` API :)

**Comment by flosse** [comment]
...but of course it's just an idea and should not lead to unnecessary workload!

**Comment by chris-rock** [comment]
@lloydwatkin I am open. What do you think?

**Comment by lloydwatkin** [comment]
Go for it :+1:

**Comment by chris-rock** [comment]
@flosse would you like to transfer your repo to node-xmpp? Afterwards we can release it and start depending on that lib

**Comment by flosse** [comment]
github tells me `You don't have admin rights to node-xmpp` if I try to transfer it :-\ So what's the way to give it away?

**Comment by lloydwatkin** [comment]
Let's sort this out at the summit.

**Comment by sonnyp** [comment]
@lloydwatkin are you talking about XMPP Summit during FOSDEM ? I'm not much interested in XMPP summit anymore but I'd love to talk/hack with you guys on node-xmpp.

**Comment by lloydwatkin** [comment]
@sonnyp I'm not talking at FOSDEM but am there. I'll probably be at the stand most of the time so please feel free to come over and say hi.

**Comment by sonnyp** [comment]
@lloydwatkin XMPP/XSF stand?

**Comment by lloydwatkin** [comment]
Yes :)

**Comment by flosse** [comment]
>  I'm not much interested in XMPP summit anymore

@sonnyp its another topic, but I'm interested: why aren't you interested anymore? I've never been to a xmpp summit, so I'm curious ;-)

**Comment by sonnyp** [comment]
@flosse https://github.com/node-xmpp/JID :)

**Comment by sonnyp** [comment]
fixed in https://github.com/node-xmpp/JID/pull/7
