### ISSUE TITLE
Connection doesn't send </stream:stream> on connection ending

### ISSUE THREAD

**Issue by Retsam** [node-xmpp/node-xmpp-core#56]
It looks like the Connection should handle the sending of the </stream:stream> stanza when the connection ends.  However, that logic is attached to the `onEnd` handler, which doesn't make sense to me.  If `onEnd` is triggered on the `end` event, then by definition isn't the socket already closed by the time the handler is called?  

Is sending the `</stream: stream>` message something the consumers of this library need to implement themselves?

Thanks

**Comment by lloydwatkin** [comment]
'end' should be triggered when there's no more data, whereas 'close' is triggered when the socket is closed.

**Comment by Retsam** [comment]
Looked into this some more; you're right about 'end' vs. 'close', but what's going on is that the connection, by default, uses a socket that doesn't allow half-opened connections, so when it receives an 'end' event, it's already sent its own 'end' event and closed its stream for writing.  This can be avoided by explicitly configuring the socket to allow half-open connections... though should `allowHalfOpen` be the default, if the behavior for sending the `</stream:stream>` message relies on it?

The other half of my issue is that, what I'm actually trying to do, is have the connection itself initiate the ending of the connection; i.e. to send the ending stream tag and then `end` the socket, but it doesn't seem that there's built-in support for that; it can only react to the other side of the socket ending the connection first.  (Though [http://xmpp.org/rfcs/rfc6120.html#streams-fundamentals](XMPP protocol) seems to indicate that both sides should send a `</stream>` when closing the connection)

**Comment by Retsam** [comment]
The issue I was seeing here has been fixed with https://github.com/node-xmpp/node-xmpp-core/pull/60
