### ISSUE TITLE
Install fails on Windows machine

### ISSUE THREAD

**Issue by liviuignat** [node-xmpp/node-xmpp-core#67]
Hi,

I am trying to install node-xmpp on a Windows 7 PC and it fails to install node-xmpp-core dependencies. As always on Windows, it seems to fail to build dependencies with node-gyp. I am running node version is 0.12.

The dependencies that fail are: node-stringprep and ltx.

Is it possible to fix this please?

Thanks.

**Comment by lloydwatkin** [comment]
Are you still trying to install the `node-xmpp` project or one of its constituent parts (-client, -component, -server)? `node-xmpp` shouldn't really be used any more and therefore has older linked dependencies.

**Comment by liviuignat** [comment]
Hi, 

I tried to build all components -client, -server, -component. They all fail installing the -core dependencies, and the -core dependency fails because of the node-stringprep and ltx dependencies.

I tried installing also node-stringprep and ltx separately and they fail on build with node-gyp.

**Comment by sonnyp** [comment]
Please report the issue to https://github.com/node-xmpp/node-stringprep
