### ISSUE TITLE
make stanza.to and stanza.from return/accept JID

### ISSUE THREAD

**Issue by sonnyp** [node-xmpp/node-xmpp-core#80]
I'm not sure this is the best idea so I'd like feedback before sending a PR.

Stanza.to and Stanza.from are getters and setters resolving to the `to` and `from` attributes. to and from on a top level stanza are always expected to be valid XMPP addresses. (reference needed :) ).

We could accept/return an instance of [JID](https://github.com/node-xmpp/JID) for both of them.

To and from getters/setters are syntactic sugar which leads me to believe it would makes sense.
```
stanza.attrs.to = new JID(to)
```
and
```
var to;
if (stanza.attrs.to) to = new JID(stanza.attrs.to)
```
is a bit painful

@lloydwatkin thoughts?

**Comment by lloydwatkin** [comment]
Sounds good, although we should break current functionality. Couldn't we
have getFrom () and getTo () which would return/accept JID objects?

**Comment by sonnyp** [comment]
@lloydwatkin fair enough

**Comment by sonnyp** [comment]
https://github.com/node-xmpp/node-xmpp-core/pull/81
